services:
  tomtroc_app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: tomtroc_app
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    networks:
      - local

networks:
  local:
    name: local
    external: true
